-- Batch 4 (2026-09-27): 20 modern stills, owner-approved.
-- Queued in a fixed order 01..20 from the 2026-09-28 morning send: last_used_at is
-- staggered at 2000-01-01 + n minutes, so they sort before every used still and
-- get_next_email_hero() takes them strictly in this order.
insert into public.email_hero_images
  (source,title,year,image_url,caption,subject_hook,style,accent,credit,active,last_used_at,use_count) values
  ('tmdb','Mission: Impossible – Dead Reckoning Part One',2023,'https://image.tmdb.org/t/p/w1280/hwinghcRR7ZJ6nqZJwd1KGZtTMn.jpg','Cruise rode that bike off a real Norwegian cliff. Years of preparation for a few seconds of film.','He rode it off a real cliff','marquee','#5D9FDD','Still: Mission: Impossible – Dead Reckoning Part One',true,timestamptz '2000-01-01 00:00+00' + interval '0 minutes',0),
  ('tmdb','Mad Max: Fury Road',2015,'https://image.tmdb.org/t/p/w1280/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg','Theron shaved her head for Furiosa and plays most of the film in near silence. Presence does the talking.','Presence does the talking','marquee','#F5D368','Still: Mad Max: Fury Road',true,timestamptz '2000-01-01 00:00+00' + interval '1 minutes',0),
  ('tmdb','Parasite',2019,'https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg','The whole house was a set built from nothing. The cast made it feel like a family had lived there for years.','The house was a set. The family felt real','latenight','#BB8B4D','Still: Parasite',true,timestamptz '2000-01-01 00:00+00' + interval '2 minutes',0),
  ('tmdb','Nomadland',2020,'https://image.tmdb.org/t/p/w1280/563sRDK3rZS31TXCdTY4lfcwrNK.jpg','Most of the people around McDormand were real nomads, playing themselves. She had to keep up with them.','Real nomads, playing themselves','marquee','#D4A68D','Still: Nomadland',true,timestamptz '2000-01-01 00:00+00' + interval '3 minutes',0),
  ('tmdb','Tár',2022,'https://image.tmdb.org/t/p/w1280/84XcRwKHAw4VXdKOYTSW5ARxFEt.jpg','Blanchett learned to conduct, and played her own piano and spoke her own German. Nobody on screen is faking the skill.','Nobody was faking the skill','latenight','#C9A24D','Still: Tár',true,timestamptz '2000-01-01 00:00+00' + interval '4 minutes',0),
  ('tmdb','Joker',2019,'https://image.tmdb.org/t/p/w1280/rlay2M5QYvi6igbGcFjq8jxeusY.jpg','Phoenix lost 52 pounds for the part. The body told half the story before he said a word.','The body told half the story','marquee','#BB4D4F','Still: Joker',true,timestamptz '2000-01-01 00:00+00' + interval '5 minutes',0),
  ('tmdb','1917',2019,'https://image.tmdb.org/t/p/w1280/2lBOQK06tltt8SQaswgb8d657Mv.jpg','Staged to look like one continuous shot. Every actor had to hit every mark, every single time.','Every mark, every time','latenight','#BB784D','Still: 1917',true,timestamptz '2000-01-01 00:00+00' + interval '6 minutes',0),
  ('tmdb','The Revenant',2015,'https://image.tmdb.org/t/p/w1280/hEQYZq2CDB2LSJVxxlazdBOKeyW.jpg','Shot almost entirely in natural light, so the cast often got one short window a day to get it right.','One short window of light a day','marquee','#509ABC','Still: The Revenant',true,timestamptz '2000-01-01 00:00+00' + interval '7 minutes',0),
  ('tmdb','Aftersun',2022,'https://image.tmdb.org/t/p/w1280/4jdduww9j5RyzO4ITRcuBFhqNN1.jpg','Frankie Corio was eleven and it was her first film. She held her own opposite Paul Mescal.','Eleven years old, first film','latenight','#BB7C4D','Still: Aftersun',true,timestamptz '2000-01-01 00:00+00' + interval '8 minutes',0),
  ('tmdb','Minari',2020,'https://image.tmdb.org/t/p/w1280/bKCpRjjTKcr3KAITmwjVMobbBYg.jpg','Shot in twenty-five days in Oklahoma, and Youn Yuh-jung walked away with an Oscar.','Twenty-five days, one Oscar','latenight','#A7C246','Still: Minari',true,timestamptz '2000-01-01 00:00+00' + interval '9 minutes',0),
  ('tmdb','The Batman',2022,'https://image.tmdb.org/t/p/w1280/mY1cGRdH2UA0uDPP8ZdLjAN9N03.jpg','Pattinson plays most of it behind a mask. Everything goes into the voice and the jaw.','Behind a mask, it all goes into the voice','latenight','#92B6D6','Still: The Batman',true,timestamptz '2000-01-01 00:00+00' + interval '10 minutes',0),
  ('tmdb','Killers of the Flower Moon',2023,'https://image.tmdb.org/t/p/w1280/acvE3RWjDLgvbL2RtcyzkrsAyNV.jpg','Lily Gladstone holds her own against De Niro and DiCaprio, mostly by staying still.','She held the screen by staying still','latenight','#D1A674','Still: Killers of the Flower Moon',true,timestamptz '2000-01-01 00:00+00' + interval '11 minutes',0),
  ('tmdb','The Iron Claw',2023,'https://image.tmdb.org/t/p/w1280/4l65BWqJBl7hBwdIwp2nQdwsOuw.jpg','The cast trained in a real ring with real wrestlers, so every hold would read as true on camera.','Every hold had to read as true','latenight','#BB7A4D','Still: The Iron Claw',true,timestamptz '2000-01-01 00:00+00' + interval '12 minutes',0),
  ('tmdb','A Real Pain',2024,'https://image.tmdb.org/t/p/w1280/fViElUGfdoZjtnVxvSpJX8TwxY6.jpg','Culkin won the Oscar playing a man who cannot sit still. Restless is a choice too.','Restless is a choice too','marquee','#BB4D6A','Still: A Real Pain',true,timestamptz '2000-01-01 00:00+00' + interval '13 minutes',0),
  ('tmdb','Arrival',2016,'https://image.tmdb.org/t/p/w1280/r8FD6CC3GgjWaGVkZh00AcedfpA.jpg','Most of Amy Adams'' performance is listening. Reacting well is half the job.','Most of the performance is listening','latenight','#E26E26','Still: Arrival',true,timestamptz '2000-01-01 00:00+00' + interval '14 minutes',0),
  ('tmdb','Sound of Metal',2019,'https://image.tmdb.org/t/p/w1280/ne0nHwHRd9PDF8YXK2IaxzujbHQ.jpg','Riz Ahmed spent months learning drums and American Sign Language before the cameras rolled.','Months of drums and sign language first','marquee','#BBB44D','Still: Sound of Metal',true,timestamptz '2000-01-01 00:00+00' + interval '15 minutes',0),
  ('tmdb','CODA',2021,'https://image.tmdb.org/t/p/w1280/v85FlkbMYKa5du1glm0YfYNsL2n.jpg','The deaf characters were played by deaf actors, and Troy Kotsur won an Oscar for it.','Cast authentically, and it won','marquee','#C67A58','Still: CODA',true,timestamptz '2000-01-01 00:00+00' + interval '16 minutes',0),
  ('tmdb','The Social Network',2010,'https://image.tmdb.org/t/p/w1280/1PXwh3nJzgRkkYnqfWInJNypeL4.jpg','Fincher shot the opening scene 99 times. The first page is where you win the room.','Ninety-nine takes of the first page','latenight','#BB874D','Still: The Social Network',true,timestamptz '2000-01-01 00:00+00' + interval '17 minutes',0),
  ('tmdb','Lady Bird',2017,'https://image.tmdb.org/t/p/w1280/jwBiY1kE5089i2WpfS1MHDYp3VO.jpg','A whole film carried on one teenager''s very specific voice. Specific always beats big.','Specific beats big','marquee','#BB714D','Still: Lady Bird',true,timestamptz '2000-01-01 00:00+00' + interval '18 minutes',0),
  ('tmdb','Ford v Ferrari',2019,'https://image.tmdb.org/t/p/w1280/2vq5GTJOahE03mNYZGxIynlHcWr.jpg','Bale lost around seventy pounds after his last role to play Ken Miles. The part decides the body.','The part decides the body','marquee','#91C1D5','Still: Ford v Ferrari',true,timestamptz '2000-01-01 00:00+00' + interval '19 minutes',0);
