-- Second seed batch for the rotating email hero (2026-09-08): +20 stills,
-- pool 32 -> 52. These go in with last_used_at NULL, and get_next_email_hero()
-- orders by "last_used_at nulls first", so every one of these 20 is shown
-- before any of the original 32 comes back around -- the noon/evening premium
-- upsell therefore opens the 9th on the new frames. No template changes.
insert into public.email_hero_images
  (source,title,year,image_url,caption,subject_hook,style,accent,credit) values
  ('tmdb','Oppenheimer',2023,'https://image.tmdb.org/t/p/w1280/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg','Nolan lit that scene with the real thing and told the cast to stop acting. Sometimes the whole note is: stop pushing.','Sometimes the whole note is — stop pushing','marquee','#D88F3C','Still: Oppenheimer'),
  ('tmdb','Everything Everywhere All at Once',2022,'https://image.tmdb.org/t/p/w1280/fIwiFha3WPu5nHkBeMQ4GzEk0Hv.jpg','Michelle Yeoh was sixty when she got the part nobody had written for her yet.','She was sixty when the part finally existed','latenight','#D0703A','Still: Everything Everywhere All at Once'),
  ('tmdb','Past Lives',2023,'https://image.tmdb.org/t/p/w1280/7HR38hMBl23lf38MAN63y4pKsHz.jpg','Two people, one bench, twenty-four years. Small scenes carry the whole film.','Small scenes carry the whole film','marquee','#D29B3A','Still: Past Lives'),
  ('tmdb','The Brutalist',2024,'https://image.tmdb.org/t/p/w1280/hmZnqijPaaACjenDkrbWcCmcADI.jpg','Brody rebuilt the accent from old family recordings. The homework never shows on screen — it just works.','The homework never shows. It just works','latenight','#AF6A35','Still: The Brutalist'),
  ('tmdb','Poor Things',2023,'https://image.tmdb.org/t/p/w1280/zh6IdheEYinU4TPtorWsjx6qPQE.jpg','She played a woman learning to speak from zero. Every sound was a decision, not an instinct.','Every sound a decision, not an instinct','marquee','#3CBED8','Still: Poor Things'),
  ('tmdb','Sing Sing',2024,'https://image.tmdb.org/t/p/w1280/8TKn3WysUAr1ZHQbZ3hODoXeI05.jpg','Most of that cast were not professional actors. They rehearsed anyway, in a circle of folding chairs.','A circle of folding chairs, and a real cast','marquee','#B2BD6C','Still: Sing Sing'),
  ('tmdb','The Holdovers',2023,'https://image.tmdb.org/t/p/w1280/57fhbxl9is7W7ur5v6UuvlNsoSg.jpg','Three people at one table for two hours. The camera never had to leave the room.','Three people, one table, two hours','latenight','#8C4F29','Still: The Holdovers'),
  ('tmdb','Anatomy of a Fall',2023,'https://image.tmdb.org/t/p/w1280/lDVl2jf6VB8ODl1olZ6FLvOV1gX.jpg','A whole trial turns on how one sentence is said the second time.','Everything turned on one sentence, said twice','marquee','#79ADD4','Still: Anatomy of a Fall'),
  ('tmdb','Whiplash',2014,'https://image.tmdb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg','His hands actually bled. Preparation is the part nobody sees at the audition.','Preparation is the part nobody sees','latenight','#B2313B','Still: Whiplash'),
  ('tmdb','Moonlight',2016,'https://image.tmdb.org/t/p/w1280/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg','Three actors, one character, and they were never in a scene together.','Three actors. One character. Never in a room together','marquee','#63D8D8','Still: Moonlight'),
  ('tmdb','Get Out',2017,'https://image.tmdb.org/t/p/w1280/bBQHALHRAaaORlPNXv7fNcRXYdx.jpg','He held the shot and let it happen without saying a word.','He held the shot and said nothing','latenight','#3B72A2','Still: Get Out'),
  ('tmdb','One Battle After Another',2025,'https://image.tmdb.org/t/p/w1280/hiazLNa1UXuX35OTnMQRKOx3eTk.jpg','The faces around the lead came out of auditions, not offers. That is still how ensembles get built.','Auditions, not offers','latenight','#D8A43C','Still: One Battle After Another'),
  ('public_domain','Battleship Potemkin',1925,'https://image.tmdb.org/t/p/w1280/sRm843SBypb9fa9t2XojoVzGNcj.jpg','Eisenstein cast faces, not resumes. Most of them had never been on a set.','He cast faces, not resumes','marquee','#B5484C','Still: Battleship Potemkin'),
  ('public_domain','Steamboat Bill, Jr.',1928,'https://image.tmdb.org/t/p/w1280/erHwsN4OrN8FReP24Pv315vzArD.jpg','The house front came down around him for real, with inches to spare. He hit his mark.','Inches to spare, and he hit his mark','marquee','#7FA0BB','Still: Steamboat Bill, Jr.'),
  ('public_domain','The Gold Rush',1925,'https://image.tmdb.org/t/p/w1280/jIqp5xXY2aw1kxnBPyCXkKQBOJ3.jpg','He rehearsed the dinner-roll dance for days to get forty seconds on screen.','Days of rehearsal, forty seconds on screen','latenight','#C9A24D','Still: The Gold Rush'),
  ('public_domain','Plan 9 from Outer Space',1959,'https://image.tmdb.org/t/p/w1280/9pHCAT1ScILdkhY8ErfOma8W4kB.jpg','Famously the worst film ever made. Everyone in it still got to say they worked.','Everyone in it still got to work','marquee','#7E6BBB','Still: Plan 9 from Outer Space'),
  ('public_domain','House on Haunted Hill',1959,'https://image.tmdb.org/t/p/w1280/lMFZsHmBvzGwNoQ0bf38Uwmi7sU.jpg','Fifteen days of shooting, under $200,000, and a year of full houses.','Fifteen days, and a year of full houses','latenight','#A54B7A','Still: House on Haunted Hill'),
  ('public_domain','The Last Man on Earth',1964,'https://image.tmdb.org/t/p/w1280/9IApWHVAtkXuVdSOnvji3n5zLcq.jpg','One actor, an empty city, nobody to play against. Some scenes you carry alone.','Some scenes you carry alone','latenight','#9F765C','Still: The Last Man on Earth'),
  ('public_domain','Meet John Doe',1941,'https://image.tmdb.org/t/p/w1280/fy2hkQgAWj1st3FWBzqc27JlytC.jpg','The whole plot starts with somebody answering an ad. It still works that way.','It still starts with answering the ad','marquee','#D67B73','Still: Meet John Doe'),
  ('tmdb','Blade Runner 2049',2017,'https://image.tmdb.org/t/p/w1280/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg','She played most of those scenes opposite a mark on a wall, and it still reads as love.','She played love opposite a mark on a wall','latenight','#BF3583','Still: Blade Runner 2049')
on conflict do nothing;
